sudo: required

dist: trusty

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

language: node_js

node_js:
  - "node"

branches:
  only:
    - master

before_script:
  - npm install -g @angular/cli

install:
  - npm install

script:
  - npm run test
