language: node_js
node_js:
  - '10'
dist: trusty
sudo: required
branches:
  only:
    - master
before_script:
  - npm install -g @angular/cli@8.1.1

install:
  - npm install

script:
  - ng test lc-datepicker-library --watch=false
