language: node_js
node_js:
  - "node"

branches:
  only:
    - master

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
  - npm install -g @angular/cli@8.1.1

install:
  - npm install

script:
  - ng test lc-datepicker-library --watch=false
